### ISSUE TITLE
Save to Subfolder

### ISSUE THREAD

**Issue by harryRichardIzquierdo** [vdsabev/image-downloader#13]
I have problems when keeping in an absolute route, I am doing it from a MAC in Chorme v49.0.2623.87, not that he is bad.

/Users/harryizquierdo/Documents/Ebooks/Modelo/

Excuses by my English.

**Comment by vdsabev** [comment]
As described in [chrome.downloads.onDeterminingFilename](https://developer.chrome.com/extensions/downloads#property-DownloadItem-filename):
> The `DownloadItem`'s new target `DownloadItem.filename`, as a path relative to the user's default Downloads directory, possibly containing subdirectories. **Absolute paths**, empty paths, and paths containing back-references ".." **will be ignored**.

So Chrome doesn't support downloading to an absolute path. Extensions can only save downloads to the **Downloads** folder, or one of its subfolders.

Also see this Chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=290562
