### ISSUE TITLE
plugin

### ISSUE THREAD

**Issue by sanakhan123** [vdsabev/image-downloader#14]
hi
i have a plugin for my web which adds images from bing, i want it to grab credit file along with the images , can you do this

**Comment by vdsabev** [comment]
I'm not sure I understand what you need, can you provide any additional details? You want to download some other files than the images?
It would be very helpful if you can send an example URL and attach some screenshots to illustrate your use case.

**Comment by sanakhan123** [comment]
I meant to say if it is possible to use the plugin within wordpress for grabbing and uploading images in the content.

**Comment by vdsabev** [comment]
This extension is for downloading images from web pages. Please provide a more detailed description of your issue, along with a URL to the site in question.
