### ISSUE TITLE
How does the renaming work?

### ISSUE THREAD

**Issue by smlombardi** [vdsabev/image-downloader#27]
Are there placeholders, e.g. date/time?  Is there a way to add to the original filenames (e.g. original files are "01.jpg, 02.jpg" but I want "myfile01.jpg, myfile02.jpg")?

**Comment by BrockA** [comment]
@smlombardi, See [pull request 20](https://github.com/vdsabev/image-downloader/pull/20).  The rename functionality is very primitive.

1. Type a string into the "RENAME FILES" input.  For example, enter "cat pics".

**Comment by BrockA** [comment]
@smlombardi, See [pull request 20](https://github.com/vdsabev/image-downloader/pull/20).  The rename functionality is very primitive.

1. Type a string into the "RENAME FILES" input.  For example, enter "cat pics".
1. Select your images and press "DOWNLOAD".
1. The files will be crudely renamed, preserving the file extension, and merely appending a number to the string entered in step 1.

For example the downloaded files will be named:  "cat pics1.jpg", "cat pics2.jpg", "cat pics3.jpg", etc.
